Repository Gui25Reis/Catapimbas, pull requests merged in 2021-11, with the labels that each got.

#19 Feat/logica catapimbas
  server/Carta.py
  server/Jogador.py
  server/Mesa.py
  server/__pycache__/Baralho.cpython-38.pyc
  server/__pycache__/Carta.cpython-38.pyc
  server/__pycache__/Jogador.cpython-38.pyc
  server/__pycache__/Mesa.cpython-38.pyc
  server/logica/Card.py
  server/logica/Deck.py
  server/logica/Game.py
  server/logica/Player.py
  server/logica/__pycache__/Card.cpython-39.pyc
  server/logica/__pycache__/Deck.cpython-39.pyc
  server/logica/__pycache__/Game.cpython-39.pyc
  server/logica/__pycache__/Player.cpython-39.pyc
  server/logica/main.py
  server/main.py
Labels: novo

#20 Feat/logica catapimbas
  server/logica/Player.py
  server/logica/__pycache__/Card.cpython-39.pyc
  server/logica/__pycache__/Deck.cpython-39.pyc
  server/logica/__pycache__/Game.cpython-39.pyc
  server/logica/__pycache__/Player.cpython-39.pyc
  server/logica/main.py
Labels: novo

#22 Created Catapimbas splash art for github README
  SplashArt.png
Labels: documentação

#23 Tirando pasta .vscode
  .gitignore
Labels: bug

#24 Feat/readme
  README.md
  arquivos/imagens/Capa-GitHub.png
Labels: documentação
